import { type NextPage } from "next";
import Head from "next/head";
import { ProductList } from "~/features/home/components/ProductList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-2xl py-6 px-3">
        <ProductList />
      </div>
    </>
  );
};

export default Home;
